# Generated by Django 5.1.4 on 2024-12-20 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="details_url",
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
