# Generated by Django 5.1.4 on 2024-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_job_details_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="details_url",
            field=models.TextField(),
        ),
    ]
