# Generated by Django 5.1.4 on 2024-12-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_job_details_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_logo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="employment_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="work_from_home_availability",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
